// seed/docentes.seed.ts
export const docentesSeed = [
  {
    nombreDocente: 'Juan',
    apellidoDocente: 'Pérez',
    identificacion: '12345678',
    carrera: 'Ingeniería en Sistemas',
    telefono: '0987654321',
    descripcion: 'Docente de Matemáticas y Física',
    estado: 'Libre',
    correo: 'asdasd@gmail.com',
  },
  {
    nombreDocente: 'Juan',
    apellidoDocente: 'Pérez',
    identificacion: '123456789',
    correo: 'juan.perez@example.com',
    carrera: 'Ingeniería',
    telefono: '555-1234',
    descripcion: 'Docente de matemáticas',
    estado: 'Activo',
  },

  {
    nombreDocente: 'María',
    apellidoDocente: 'Pérez',
    identificacion: '98765432',
    carrera: 'Biología',
    telefono: '0912345678',
    descripcion: 'Docente de Biología',
    estado: 'Ocupado',
    correo: 'asdasd@gmail.com',
  },
  {
    nombreDocente: 'Juan',
    apellidoDocente: 'Pérez',
    identificacion: '1234567890',
    correo: 'juan.perez@example.com',
    carrera: 'Ingeniería',
    telefono: '555-1234',
    descripcion: 'Docente de matemáticas',
    estado: 'Activo',
  },
  {
    nombreDocente: 'Laura',
    apellidoDocente: 'Pérez',
    identificacion: '1357924680',
    correo: 'laura.martinez@example.com',
    carrera: 'Ciencias Ambientales',
    telefono: '555-2468',
    descripcion: 'Docente de ecología',
    estado: 'Activo',
  },
  {
    nombreDocente: 'Ana',
    apellidoDocente: 'Pérez',
    identificacion: '9753108642',
    correo: 'ana.sanchez@example.com',
    carrera: 'Biología',
    telefono: '555-3210',
    descripcion: 'Docente de biología molecular',
    estado: 'Activo',
  },
  {
    nombreDocente: 'Elena',
    apellidoDocente: 'Pérez',
    identificacion: '5082467913',
    correo: 'elena.gomez@example.com',
    carrera: 'Artes Escénicas',
    telefono: '555-4567',
    descripcion: 'Docente de teatro',
    estado: 'Activo',
  },
  {
    nombreDocente: 'Fernando',
    apellidoDocente: 'Pérez',
    identificacion: '7034285619',
    correo: 'fernando.castro@example.com',
    carrera: 'Psicología',
    telefono: '555-8901',
    descripcion: 'Docente de psicoterapia',
    estado: 'Activo',
  },
  {
    nombreDocente: 'Mónica',
    apellidoDocente: 'Pérez',
    identificacion: '6143209578',
    correo: 'monica.rios@example.com',
    carrera: 'Comunicación Social',
    telefono: '555-2345',
    descripcion: 'Docente de periodismo',
    estado: 'Inactivo',
  },
];
