// seed/eventos.seed.ts
export const eventosSeed = [
  {
    titulo: 'Taller de Fotografía',
    descripcion: 'Taller práctico para aprender técnicas de fotografía',
    duracion: 5,
    fecha: '2023-08-05',
    imgen: 'taller-fotografia.jpg',
    estado: 'Programado',
    inicioHora: '09:00',
  },

  {
    titulo: 'Concierto de Música Clásica',
    descripcion: 'Concierto de música clásica con obras de Beethoven y Mozart',
    duracion: 5,
    fecha: '2023-08-10',
    imgen: 'concierto-musica-clasica.png',
    estado: 'Programado',
    inicioHora: '18:30',
  },
  {
    titulo: 'Seminario de Marketing Digital',
    descripcion: 'Seminario sobre estrategias de marketing digital',
    duracion: 5,
    fecha: '2023-08-15',
    imgen: 'seminario-marketing-digital.jpg',
    estado: 'Programado',
    inicioHora: '10:00',
  },
  {
    titulo: 'Exposición de Arte Contemporáneo',
    descripcion: 'Exposición de obras de artistas contemporáneos',
    duracion: 5,
    fecha: '2023-08-20',
    imgen: 'exposicion-arte-contemporaneo.png',
    estado: 'Programado',
    inicioHora: '16:00',
  },
  {
    titulo: 'Conferencia de Ciencias Ambientales',
    descripcion: 'Conferencia sobre conservación del medio ambiente',
    duracion: 5,
    fecha: '2023-08-25',
    imgen: 'conferencia-ciencias-ambientales.jpg',
    estado: 'Programado',
    inicioHora: '14:00',
  },
  {
    titulo: 'Taller de Cocina',
    descripcion:
      'Taller práctico para aprender recetas de cocina internacional',
    duracion: 5,
    fecha: '2023-09-02',
    imgen: 'taller-cocina.jpg',
    estado: 'Programado',
    inicioHora: '11:00',
  },
  {
    titulo: 'Concierto de Rock',
    descripcion: 'Concierto de bandas de rock locales',
    duracion: 5,
    fecha: '2023-09-10',
    imgen: 'concierto-rock.png',
    estado: 'Programado',
    inicioHora: '20:00',
  },
  {
    titulo: 'Seminario de Liderazgo',
    descripcion: 'Seminario para desarrollar habilidades de liderazgo',
    duracion: 5,
    fecha: '2023-09-15',
    imgen: 'seminario-liderazgo.jpg',
    estado: 'Programado',
    inicioHora: '09:30',
  },
  {
    titulo: 'Feria de Emprendimiento',
    descripcion: 'Feria para promover emprendimientos locales',
    duracion: 5,
    fecha: '2023-09-25',
    imgen: 'feria-emprendimiento.jpg',
    estado: 'Programado',
    inicioHora: '09:00',
  },
];
